### ISSUE TITLE
An RFC on RFCs

### ISSUE THREAD

**Issue by Illizian** [NorfolkDev/rfc#1]
Request for comments on how we handle RFCs within this repository.

1. Draft an RFC as an Issue, formalise with a PR `texts/0001-rfc-on-rfcs.md`
2. Submit a new `texts/0001-rfc-on-rfcs.md` as a PR, discuss on PR
3. Enable [GitHub Discussions ](https://docs.github.com/en/discussions) for the repository.
4. Other...

**Comment by R-Saunders** [comment]
I really like this. I may have an RFC or two myself ☺️

**Comment by Illizian** [comment]
> I really like this. I may have an RFC or two myself relaxed

Excellent, how would you feel most comfortable submitting these though?

**Comment by R-Saunders** [comment]
> > I really like this. I may have an RFC or two myself relaxed
> 
> Excellent, how would you feel most comfortable submitting these though?

I misread that. So I like the idea of GitHub discussions. I feel issues and PRS should be kept for changes to the website and the code rather than RFCs that relate to other things like the discord, community events or the conference etcetera.

**Comment by tom-sherman** [comment]
I'd advocate for PRs. Firstly there's a lot of prior art here eg. https://github.com/reactjs/rfcs and https://github.com/rust-lang/rfcs

One of the things PRs enable is having a clear "end state" to a discussion or suggestion. Something that's not ideal about actions at the moment is that things are agreed upon but it's not clear, even in the mods team, what the next steps are.

With this in mind I'd propose a very simple process of:

1. Open RFC by creating a PR of a markdown file (a la the react RFC process)
2. Reach consensus. This is intentionally nebulous to begin with, we can refine this over time if we feel like stalled RFCs are a problem.
3. Either close or merge the RFC

Another issue with GitHub discussions is that they're mutable. Merged RFCs are a single immutable decision frozen in time. If we want to revise this decision at a later date we can create a new RFC that supersedes it. This links to having a clear "end state" too and separates the decision from the discussion.

**Comment by R-Saunders** [comment]
> I'd advocate for PRs. Firstly there's a lot of prior art here eg. https://github.com/reactjs/rfcs and https://github.com/rust-lang/rfcs
> 
> One of the things PRs enable is having a clear "end state" to a discussion or suggestion. Something that's not ideal about actions at the moment is that things are agreed upon but it's not clear, even in the mods team, what the next steps are.
> 
> With this in mind I'd propose a very simple process of:
> 
> 1. Open RFC by creating a PR of a markdown file (a la the react RFC process)
> 2. Reach consensus. This is intentionally nebulous to begin with, we can refine this over time if we feel like stalled RFCs are a problem.
> 3. Either close or merge the RFC
> 
> Another issue with GitHub discussions is that they're mutable. Merged RFCs are a single immutable decision frozen in time. If we want to revise this decision at a later date we can create a new RFC that supersedes it. This links to having a clear "end state" too and separates the decision from the discussion.

The issue I have with PR's for this is that they seem very much focused on what's in the repo. Discord isn't in the repo. Neither are other community things. Only the website is. Would we add some stuff to the repo as documentation for said things so it can be discussed and we have a record of what's already in place? (I may be missing something here, I'm still new to GitHub etc).

**Comment by tom-sherman** [comment]
The repo in question here (the one we're discussing in) is seperate from the website or conferences websites, or any other code for that matter. This is a good thing, it allows a single RFC to address discord and the website for example.

This is the case for the two examples I posted too. React and Rust RFCs are discussing changes to the code and architecture but also their respective communities.

**Comment by R-Saunders** [comment]
> The repo in question here (the one we're discussing in) is seperate from the website or conferences websites, or any other code for that matter. This is a good thing, it allows a single RFC to address discord and the website for example.
> 
> This is the case for the two examples I posted too. React and Rust RFCs are discussing changes to the code and architecture but also their respective communities.

🤦🏻‍♂️My bad! I didn't realise this was a separate repo. Ok so I can see it working as a PR. Personally I would like to try GitHub discussions. Couple reasons. Seems more friendly to community members who aren't developers such as content writers, UI/UX designers, recruiters etc. Also. I've never used it and want to give it a go, but that's unrelated so ignore that. Have you used discussions before?

**Comment by Illizian** [comment]
I'm in agreement with @tom-sherman, especially for audit and mutability.

I do also agree the friction of creating the PR is a problem, however, GitHub handles this well within their web UI and with a simple guide and templates this could be made easier.

**Comment by R-Saunders** [comment]
> I'm in agreement with @tom-sherman, especially for audit and mutability.
> 
> I do also agree the friction of creating the PR is a problem, however, GitHub handles this well within their web UI and with a simple guide and templates this could be made easier.
> 
> **Update:** Re. Discord, there may be a service for syncing these changes soon and the current schema is incredibly simple, intentionally, to make syncing those changes easy for a server admin.

A simple guide sounds good. Alternatively people could always reach out to a mod or another community member for help.

**Comment by Illizian** [comment]
Okee doke. I'll draft a PR for this RFC itself later today and document the process in a file in this repo.

**Comment by Illizian** [comment]
@R-Saunders & @tom-sherman I have added a suggested format & process on #2
